#!/bin/sh
set -e
/app/set_config.sh

export APACHE_RUN_DIR=/var/run/apache2
export APACHE_ARGUMENTS="-DFOREGROUND $@"

# Apache gets grumpy about PID files pre-existing
rm -f ${APACHE_RUN_DIR}/apache2.pid

exec /usr/sbin/apachectl start
